Update patch set 3
Patch Set 3:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//100454-3/index.html
______________ Results _________________
************ Infrastructure-healthcheck Results ************
--------> onap-k8s
 * Nb Pods: 228
 * Nb Failed Pods: 16
 * List of Failed Pods: [
   - onap-aaf-aaf-gui-c8b9f4b6f-bnprx
   - onap-aaf-aaf-sms-c94596d94-4bh6n
   - onap-aai-aai-7444d6c5bf-b29n5
   - onap-aai-aai-sparky-be-644f79c9bd-c2kbr
   - onap-aai-aai-traversal-74c8cc4895-lwxkt
   - onap-contrib-netbox-app-f44957948-2zvk6
   - onap-dmaap-dmaap-dr-prov-5b46b4979d-jhvf9
   - onap-nbi-nbi-6c5b887cf7-vc4fk
   - onap-oof-oof-86c448d5c7-mzhdg
   - onap-oof-oof-cmso-optimizer-5884678759-9ksgr
   - onap-oof-oof-cmso-service-66ff6f6cd8-25ntc
   - onap-oof-oof-has-api-5bb7b84888-szx2j
   - onap-oof-oof-has-controller-56f598fb9f-kt2ss
   - onap-oof-oof-has-data-d575ff6df-btmgm
   - onap-oof-oof-has-reservation-547c8f4d7f-qt4d9
   - onap-oof-oof-has-solver-746bff67d8-br6zc]
--------> onap-helm
 * Nb Helm Charts: 36
 * Nb Failed Helm Charts: 0
 * List of Failed Helm Charts: []
************************************************************
********************* Healthcheck Results ******************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-01-23 01:31:24,883 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
"SO DISTRIBUTION_COMPLETE_ERROR"

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-01-23 01:27:39,863 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/v16/service-design-and-creation/models/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f042141bd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml
************************************************************
********************** Smoke usecases **********************
End to End VNF use cases not executed!
____________________________________

Patch-set: 3