Update patch set 2
Patch Set 2:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > (1 comment)
> 
> We have seen that before in slow deployments; we thought we had already fixed that but I'll submit a patch to increase the initalDelaySeconds on the readiness probe

Thanks for help. Unfortunately raising initial delay didn't help. Actually, data-router is in crashLoop due to container failing, not liveness probe. Please take a look at pod description below:

>   aai-data-router:
>     Container ID:   docker://b3d2cc353cf1cdc8d123e6741eca26ddb3d87e45c071b434a5917e50a035f078
>     Image:          nexus3.onap.org:10001/onap/data-router:1.6.2
>     Image ID:       docker-pullable://nexus3.onap.org:10001/onap/data-router@sha256:ddbfd0866608cabeb942ee76acc1f221c2cf6a6322ff3ee2bd328a3e8af06540
>     Port:           9502/TCP
>     Host Port:      0/TCP
>     State:          Waiting
>       Reason:       CrashLoopBackOff
>     Last State:     Terminated
>       Reason:       Error
>       Exit Code:    1
>       Started:      Fri, 03 Apr 2020 17:41:11 +0200
>       Finished:     Fri, 03 Apr 2020 17:41:22 +0200
>     Ready:          False
>     Restart Count:  5
>     Liveness:       tcp-socket :9502 delay=300s timeout=1s period=10s #success=1 #failure=3
>     Readiness:      tcp-socket :9502 delay=120s timeout=1s period=10s #success=1 #failure=3

Pod logs are the same as previously. This time I took a deeper look and found out following error log under /opt/app/data-router/logs/AAI-DR/error.log (I've shortened traceback a little):

> 2020-04-03T15:49:05.820Z||main|data-router||org.onap.aai.datarouter.Application||INFO|Starting Application v1.6.2 on onap-aai-data-router-9c5f4b585-vf8mk with PID 6 (/opt/app/data-router/data-router.jar started by aaiadmin in /opt/app/data-router)
> 2020-04-03T15:49:05.821Z||main|data-router||org.onap.aai.datarouter.Application||INFO|No active profile set, falling back to default profiles: default
> 2020-04-03T15:49:12.835Z||main|data-router||org.springframework.beans.factory.xml.XmlBeanDefinitionReader||WARN|Ignored XML validation warning
> org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'http://www.springframework.org/schema/context/spring-context-4.2.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
>         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
>         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:99)
> ...
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
>         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
> Caused by: java.net.UnknownHostException: www.springframework.org
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> ...
>         at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2181)
>         ... 48 common frames omitted
> 2020-04-03T15:49:12.837Z||main|data-router||org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext||WARN|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 10 in XML document from file [/opt/app/data-router/dynamic/conf/data-router-oxm.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 38; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'context:property-placeholder'.
> 2020-04-03T15:49:12.863Z||main|data-router||org.springframework.boot.SpringApplication||ERROR|Application run failed
> org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 10 in XML document from file [/opt/app/data-router/dynamic/conf/data-router-oxm.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 38; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'context:property-placeholder'.
>         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:405)
>         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:337)
> ...
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
>         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
> Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'context:property-placeholder'.
>         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
>         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
> ...
>         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:435)
>         at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:393)
>         ... 30 common frames omitted

Patch-set: 2
Reviewer: Gerrit User 5550 <5550@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>