Update patch set 2
Patch Set 2:

> Patch Set 2: Code-Review-1
> 
> > Patch Set 2:
> > 
> > Gitlab Orange 2: 
> > Full results can be seen here: https://gating-results.onap.eu/results//105043-2/index.html
> > ______________ Results ______________________
> > 
> > ************************************************************
> > ************************************************************
> > ************ Infrastructure-healthcheck Results ************
> > ************************************************************
> > ************************************************************
> > --------> onap-k8s
> >  * Nb Jobs: 23
> >  * Nb Failed Jobs: 1
> >  * List of Failed Jobs: [
> >    - onap-oof-has-healthcheck]
> >  * Nb Deployments: 173
> >  * Nb Failed Deployments: 3
> >  * List of Failed Deployments: [
> >    - onap-oof-has-data
> >  onap-oof-has-reservation
> >  onap-oof-has-solver]
> >  * Nb StatefulSets: 32
> >  * Nb Failed StatefulSets: 0
> >  * Nb Persistent Volume Claims: 95
> >  * Nb Failed Persistent Volume Claims: 0
> > --------> onap-helm
> >  * Nb Helm Charts: 37
> >  * Nb Failed Helm Charts: 0
> >  * List of Failed Helm Charts: []
> > 
> > ************************************************************
> > ************************************************************
> > ********************* Healthcheck Results ******************
> > ************************************************************
> > ************************************************************
> > --------> robot  full healthcheck tests
> > 2020-04-06 09:28:46,074 - xtesting.core.robotframework - INFO - 
> > ==============================================================================
> > Health-Check :: Test that ONAP components are available via basic API calls   
> > ==============================================================================
> > Basic A&AI Health Check                                               | PASS |
> > ------------------------------------------------------------------------------
> > Basic AAF Health Check                                                | PASS |
> > ------------------------------------------------------------------------------
> > Basic AAF SMS Health Check                                            | PASS |
> > ------------------------------------------------------------------------------
> > Basic APPC Health Check                                               | PASS |
> > ------------------------------------------------------------------------------
> > Basic CLI Health Check                                                | FAIL |
> > ConnectionError: HTTPSConnectionPool(host='cli.onap', port=8443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb260828dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> > ------------------------------------------------------------------------------
> > Basic CLAMP Health Check                                              | PASS |
> > ------------------------------------------------------------------------------
> > Basic DCAE Health Check                                               | FAIL |
> > 500 != 200
> > ------------------------------------------------------------------------------
> > Basic DMAAP Data Router Health Check                                  | PASS |
> > ------------------------------------------------------------------------------
> > Basic DMAAP Message Router Health Check                               | PASS |
> > ------------------------------------------------------------------------------
> > Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
> > ------------------------------------------------------------------------------
> > Basic External API NBI Health Check                                   | FAIL |
> > ConnectionError: HTTPSConnectionPool(host='nbi.onap', port=8443): Max retries exceeded with url: /nbi/api/v4/status?fullStatus=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb26067ad10>: Failed to establish a new connection: [Errno 111] Connection refused'))
> > ------------------------------------------------------------------------------
> > Basic Microservice Bus Health Check                                   | PASS |
> > ------------------------------------------------------------------------------
> > Basic Multicloud API Health Check                                     | PASS |
> > ------------------------------------------------------------------------------
> > Basic Multicloud-pike API Health Check                                | PASS |
> > ------------------------------------------------------------------------------
> > Basic Multicloud-starlingx API Health Check                           | PASS |
> > ------------------------------------------------------------------------------
> > Basic Multicloud-titanium_cloud API Health Check                      | PASS |
> > ------------------------------------------------------------------------------
> > Basic Multicloud-vio API Health Check                                 | PASS |
> > ------------------------------------------------------------------------------
> > Basic Multicloud-k8s API Health Check                                 | PASS |
> > ------------------------------------------------------------------------------
> > Basic OOF-Homing Health Check                                         | FAIL |
> > 502 != 200
> > ------------------------------------------------------------------------------
> > Basic OOF-SNIRO Health Check                                          | PASS |
> > ------------------------------------------------------------------------------
> > Basic OOF-CMSO Health Check                                           | PASS |
> > ------------------------------------------------------------------------------
> > Basic Policy Health Check                                             | PASS |
> > ------------------------------------------------------------------------------
> > Basic Portal Health Check                                             | PASS |
> > ------------------------------------------------------------------------------
> > Basic SDC Health Check                                                | PASS |
> > ------------------------------------------------------------------------------
> > Basic SDNC Health Check                                               | PASS |
> > ------------------------------------------------------------------------------
> > Basic SO Health Check                                                 | PASS |
> > ------------------------------------------------------------------------------
> > Basic UseCaseUI API Health Check                                      | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC emsdriver API Health Check                                  | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC gvnfmdriver API Health Check                                | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC huaweivnfmdriver API Health Check                           | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC jujuvnfmdriver API Health Check                             | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC multivimproxy API Health Check                              | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC nokiav2driver API Health Check                              | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC nslcm API Health Check                                      | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC resmgr API Health Check                                     | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC vnflcm API Health Check                                     | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC vnfmgr API Health Check                                     | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC vnfres API Health Check                                     | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC workflow API Health Check                                   | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC ztesdncdriver API Health Check                              | PASS |
> > ------------------------------------------------------------------------------
> > Basic VFC ztevnfmdriver API Health Check                              | PASS |
> > ------------------------------------------------------------------------------
> > Basic VID Health Check                                                | PASS |
> > ------------------------------------------------------------------------------
> > Basic VNFSDK Health Check                                             | PASS |
> > ------------------------------------------------------------------------------
> > Basic Multicloud-fcaps API Health Check                               | PASS |
> > ------------------------------------------------------------------------------
> > Basic Modeling genericparser API Health Check                         | PASS |
> > ------------------------------------------------------------------------------
> > Basic CDS Health Check                                                | PASS |
> > ------------------------------------------------------------------------------
> > Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> > 46 critical tests, 42 passed, 4 failed
> > 46 tests total, 42 passed, 4 failed
> > ==============================================================================
> > Output:  /var/lib/xtesting/results/full/output.xml
> > --------> healthdist (vFW onboarding and distribution)
> > --------> postinstall tests (dmaap and A&AI)
> > 2020-04-06 09:26:40,874 - xtesting.core.robotframework - INFO - 
> > ==============================================================================
> > Post-Install-Tests :: Testing Installation                                    
> > ==============================================================================
> > Basic DMAAP Message Router ACL Update Test                            | PASS |
> > ------------------------------------------------------------------------------
> > Basic AAI Service Design Models Size Test                             | PASS |
> > ------------------------------------------------------------------------------
> > Post-Install-Tests :: Testing Installation                            | PASS |
> > 2 critical tests, 2 passed, 0 failed
> > 2 tests total, 2 passed, 0 failed
> > ==============================================================================
> > Output:  /var/lib/xtesting/results/postinstall/output.xml
> > 
> > 
> > ************************************************************
> > ************************************************************
> > ********************** Smoke usecases **********************
> > ************************************************************
> > ************************************************************
> > --------> End to End tests (onap-tests)
> > freeradius_nbi: FAIL (00:04)
> > clearwater_ims: FAIL (00:05)
> > 
> > ************************************************************
> > ************************************************************
> > ********************** Security tests **********************
> > ************************************************************
> > ************************************************************
> > cis_kubernetes: FAIL (00:02)
> > http_public_endpoints: FAIL (02:05)
> > jdpw_ports: FAIL (06:07)
> > kube_hunter: FAIL (00:13)
> > root_pods: FAIL (03:59)
> > unlimitted_pods: FAIL (00:45)
> > 
> > --------> FOCUS on CIS errors
> > Test FAIL: 33 assertions not passed
> > [FAIL] 1.1.9 Ensure that the --repair-malformed-updates argument is set to false (Scored)
> > [FAIL] 1.1.11 Ensure that the admission control plugin AlwaysPullImages is set (Scored)
> > [FAIL] 1.1.15 Ensure that the --audit-log-path argument is set as appropriate (Scored)
> > [FAIL] 1.1.16 Ensure that the --audit-log-maxage argument is set to 30 or as appropriate (Scored)
> > [FAIL] 1.1.17 Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate (Scored)
> > [FAIL] 1.1.18 Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate (Scored)
> > [FAIL] 1.1.21 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Scored)
> > [FAIL] 1.1.24 Ensure that the admission control plugin PodSecurityPolicy is set (Scored)
> > [FAIL] 1.1.34 Ensure that the --encryption-provider-config argument is set as appropriate (Scored)
> > [FAIL] 1.1.36 Ensure that the admission control plugin EventRateLimit is set (Scored)
> > [FAIL] 1.1.37b Ensure that the AdvancedAuditing argument is not set to false (Scored)
> > [FAIL] 1.2.1 Ensure that the --profiling argument is set to false (Scored)
> > [FAIL] 1.3.6 Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)
> > [FAIL] 1.4.1 Ensure that the API server pod specification file permissions are set to 644 or more restrictive (Scored)
> > [FAIL] 1.4.2 Ensure that the API server pod specification file ownership is set to root:root (Scored)
> > [FAIL] 1.4.3 Ensure that the controller manager pod specification file permissions are set to 644 or more restrictive (Scored)
> > [FAIL] 1.4.4 Ensure that the controller manager pod specification file ownership is set to root:root (Scored)
> > [FAIL] 1.4.5 Ensure that the scheduler pod specification file permissions are set to 644 or more restrictive (Scored)
> > [FAIL] 1.4.6 Ensure that the scheduler pod specification file ownership is set to root:root (Scored)
> > [FAIL] 1.4.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)
> > [FAIL] 1.4.8 Ensure that the etcd pod specification file ownership is set to root:root (Scored)
> > [FAIL] 1.4.11 Ensure that the etcd data directory permissions are set to 700 or more restrictive (Scored)
> > [FAIL] 1.4.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)
> > [FAIL] 1.4.13 Ensure that the admin.conf file permissions are set to 644 or more restrictive (Scored)
> > [FAIL] 1.4.14 Ensure that the admin.conf file ownership is set to root:root (Scored)
> > [FAIL] 1.4.15 Ensure that the scheduler.conf file permissions are set to 644 or more restrictive (Scored)
> > [FAIL] 1.4.16 Ensure that the scheduler.conf file ownership is set to root:root (Scored)
> > [FAIL] 1.4.17 Ensure that the controller-manager.conf file permissions are set to 644 or more restrictive (Scored)
> > [FAIL] 1.4.18 Ensure that the controller-manager.conf file ownership is set to root:root (Scored)
> > [FAIL] 1.5.1 Ensure that the --cert-file and --key-file arguments are set as appropriate (Scored)
> > [FAIL] 1.5.2 Ensure that the --client-cert-auth argument is set to true (Scored)
> > [FAIL] 1.5.4 Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate (Scored)
> > [FAIL] 1.5.5 Ensure that the --peer-client-cert-auth argument is set to true (Scored)
> > 33 checks FAIL
> > 
> > ____________________________________________________________
> 
> seems to break the distribution
> - no healthdist results (misleading in teh dashboard -> test crashed, no results produced (keep green by default)) but if you look at the console or the log (https://gating-results.onap.eu/results//105043-2/healthcheck/healthdist/xtesting.log) you can see that this new A&AI prevents the onboarding/distribution (was OK on current Master run)
> - E2E tests are crashing very early
> 
> the question is 
> - is it a bug/regression/API change inA&AI or are the tests (healthdist/End to End tests not updated according to new A&AI changes)
> in other words
> shall we merge and troubleshoot on Master
> Or shall we fix it on this patch then merge

Is there a way we can see the healthdist results?  My WR environment can't do a full healthdist since it's a limited deployment.

Patch-set: 2